[env]
AR_aarch64-linux-android = "llvm-ar"                          # ndk-25c/api-28
AR_x86_64-linux-android = "llvm-ar"                           # ndk-25c/api-28
CC = "clang-17"                                               # for C/C++ deps
CC_aarch64-linux-android = "aarch64-linux-android28-clang"    # ndk-25c/api-28
CC_x86_64-linux-android = "aarch64-linux-android28-clang"     # ndk-25c/api-28
CXX = "clang-17"                                              # for C/C++ deps
CXX_aarch64-linux-android = "aarch64-linux-android28-clang++" # ndk-25c/api-28
CXX_x86_64-linux-android = "aarch64-linux-android28-clang++"  # ndk-25c/api-28

[target.aarch64-linux-android]
linker = "aarch64-linux-android28-clang" # ndk-25c/api-28

[target.x86_64-linux-android]
linker = "x86_64-linux-android28-clang" # ndk-25c/api-28

[profile.dev]
codegen-units = 16
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = "unwind"
rpath = false

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "thin"
opt-level = 3
overflow-checks = false
panic = "unwind"
rpath = false
strip = "symbols"

[profile.test]
codegen-units = 256
debug = 2
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
rpath = false

[profile.bench]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
rpath = false
strip = "symbols"
